name = "Tune"
uuid = "fedcd5e3-25fa-4517-9d96-0ffbee4aa29d"
authors = ["Peter Ahrens"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
